# The prefix that appears in front of every message sent by the server
system_prefix: KissenPvP
# The section defining default appearance settings for players
appearance:
    # The primary color used for player-related elements (e.g. highlights)
    primary: yellow
    # The secondary color used for additional player-related elements (e.g., secondary highlights, less prominent elements)
    secondary: gold
    # The general color used for neutral or less specific elements
    general: gray
    # The color indicating an enabled state or active status
    enabled: green
    # The color indicating a disabled state or inactive status
    disabled: red
