name: Visual
main: net.kissenpvp.visual.InternalVisual
version: '${version}'
description: Enables servers to alter the tab list and chat based on prefix and suffixes.
author: DevLucas
api-version: '1.21'
